<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\AppService\" />
    <Folder Include="wwwroot\videos\" />
    <Folder Include="wwwroot\pics\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\rs-plugin\js\.DS_Store" />
  </ItemGroup>
	
	  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\App.Domai.AppServices\App.Domain.AppServices.csproj" />
    <ProjectReference Include="..\..\..\App.Domai.Services\App.Domain.Services.csproj" />
    <ProjectReference Include="..\..\..\App.Domain.Core\App.Domain.Core.csproj" />
    <ProjectReference Include="..\App.Infarstructure.DataBase.SqlServer\App.Infarstructure.DataBase.SqlServer.csproj" />
  </ItemGroup>

</Project>
