// <auto-generated />
using System;
using App.Infarstructure.DataBase.SqlServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infarstructure.DataBase.SqlServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928184013_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colours");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisLikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("EditoroperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastEditTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("SubmitUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EditoroperatorId" }, "IX_Comments_EditoroperatorId");

                    b.HasIndex(new[] { "ParentCommentId" }, "IX_Comments_ParentCommentId");

                    b.HasIndex(new[] { "ProductId" }, "IX_Comments_ProductId");

                    b.HasIndex(new[] { "StatusId" }, "IX_Comments_StatusId");

                    b.HasIndex(new[] { "SubmitUserId" }, "IX_Comments_SubmitUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.EditorOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EditorOperators");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValidExtentions")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("FileTypes");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ForComment")
                        .HasColumnType("bit");

                    b.Property<bool>("ForProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.SubmitOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubmitOperators");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.SubmitUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubmitUsers");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.ViewrUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViewrUsers");
                });

            modelBuilder.Entity("App.Domain.Core.Brand.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ParentCategoryId" }, "IX_Categories_ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.CollectionProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CollectionId" }, "IX_CollectionProducts_CollectionId");

                    b.HasIndex(new[] { "ProductId" }, "IX_CollectionProducts_ProductId");

                    b.ToTable("CollectionProducts");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("BrandId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BrandId" }, "IX_Models_BrandId");

                    b.HasIndex(new[] { "BrandId1" }, "IX_Models_BrandId1");

                    b.HasIndex(new[] { "ParentModelId" }, "IX_Models_ParentModelId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShowPrice")
                        .HasColumnType("bit");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("SubmitOperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BrandId" }, "IX_Products_BrandId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Products_CategoryId");

                    b.HasIndex(new[] { "ModelId" }, "IX_Products_ModelId");

                    b.HasIndex(new[] { "SubmitOperatorId" }, "IX_Products_SubmitOperatorId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<bool>("IsExist")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ColourId" }, "IX_ProductColours_ColourId");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductColours_ProductId");

                    b.ToTable("ProductColours");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FileTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FileTypeId" }, "IX_ProductFiles_FileTypeId");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductFiles_ProductId");

                    b.ToTable("ProductFiles");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductTags_ProductId");

                    b.HasIndex(new[] { "TagId" }, "IX_ProductTags_TagId");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ViewerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Viewtime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductViews_ProductId");

                    b.HasIndex(new[] { "ViewerUserId" }, "IX_ProductViews_ViewerUserId");

                    b.ToTable("ProductViews");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasValue")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TagCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TagCategoryId" }, "IX_Tags_TagCategoryId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TagCategories");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.Comment", b =>
                {
                    b.HasOne("App.Domain.Core.BaseData.Entities.EditorOperator", "Editoroperator")
                        .WithMany("Comments")
                        .HasForeignKey("EditoroperatorId");

                    b.HasOne("App.Domain.Core.BaseData.Entities.Comment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("App.Domain.Core.Product.Entities.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.BaseData.Entities.Status", "Status")
                        .WithMany("Comments")
                        .HasForeignKey("StatusId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.BaseData.Entities.SubmitUser", "SubmitUser")
                        .WithMany("Comments")
                        .HasForeignKey("SubmitUserId")
                        .IsRequired();

                    b.Navigation("Editoroperator");

                    b.Navigation("ParentComment");

                    b.Navigation("Product");

                    b.Navigation("Status");

                    b.Navigation("SubmitUser");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Category", b =>
                {
                    b.HasOne("App.Domain.Core.Product.Entities.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.CollectionProduct", b =>
                {
                    b.HasOne("App.Domain.Core.Product.Entities.Collection", "Collection")
                        .WithMany("CollectionProducts")
                        .HasForeignKey("CollectionId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Product.Entities.Product", "Product")
                        .WithMany("CollectionProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Model", b =>
                {
                    b.HasOne("App.Domain.Core.Brand.Entities.Brand", "Brand")
                        .WithMany("ModelBrands")
                        .HasForeignKey("BrandId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Brand.Entities.Brand", "BrandId1Navigation")
                        .WithMany("ModelBrandId1Navigations")
                        .HasForeignKey("BrandId1");

                    b.HasOne("App.Domain.Core.Product.Entities.Model", "ParentModel")
                        .WithMany("InverseParentModel")
                        .HasForeignKey("ParentModelId");

                    b.Navigation("Brand");

                    b.Navigation("BrandId1Navigation");

                    b.Navigation("ParentModel");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Product", b =>
                {
                    b.HasOne("App.Domain.Core.Brand.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Product.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Product.Entities.Model", "Model")
                        .WithMany("Products")
                        .HasForeignKey("ModelId");

                    b.HasOne("App.Domain.Core.BaseData.Entities.SubmitOperator", "SubmitOperator")
                        .WithMany("Products")
                        .HasForeignKey("SubmitOperatorId")
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Model");

                    b.Navigation("SubmitOperator");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductColour", b =>
                {
                    b.HasOne("App.Domain.Core.BaseData.Entities.Colour", "Colour")
                        .WithMany("ProductColours")
                        .HasForeignKey("ColourId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Product.Entities.Product", "Product")
                        .WithMany("ProductColours")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductFile", b =>
                {
                    b.HasOne("App.Domain.Core.BaseData.Entities.FileType", "FileType")
                        .WithMany("ProductFiles")
                        .HasForeignKey("FileTypeId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Product.Entities.Product", "Product")
                        .WithMany("ProductFiles")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("FileType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductTag", b =>
                {
                    b.HasOne("App.Domain.Core.Product.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Product.Entities.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.ProductView", b =>
                {
                    b.HasOne("App.Domain.Core.Product.Entities.Product", "Product")
                        .WithMany("ProductViews")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("App.Domain.Core.BaseData.Entities.ViewrUser", "ViewerUser")
                        .WithMany("ProductViews")
                        .HasForeignKey("ViewerUserId")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ViewerUser");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Tag", b =>
                {
                    b.HasOne("App.Domain.Core.Product.Entities.TagCategory", "TagCategory")
                        .WithMany("Tags")
                        .HasForeignKey("TagCategoryId")
                        .IsRequired();

                    b.Navigation("TagCategory");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.Colour", b =>
                {
                    b.Navigation("ProductColours");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.Comment", b =>
                {
                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.EditorOperator", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.FileType", b =>
                {
                    b.Navigation("ProductFiles");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.Status", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.SubmitOperator", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.SubmitUser", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("App.Domain.Core.BaseData.Entities.ViewrUser", b =>
                {
                    b.Navigation("ProductViews");
                });

            modelBuilder.Entity("App.Domain.Core.Brand.Entities.Brand", b =>
                {
                    b.Navigation("ModelBrandId1Navigations");

                    b.Navigation("ModelBrands");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Category", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Collection", b =>
                {
                    b.Navigation("CollectionProducts");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Model", b =>
                {
                    b.Navigation("InverseParentModel");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Product", b =>
                {
                    b.Navigation("CollectionProducts");

                    b.Navigation("Comments");

                    b.Navigation("ProductColours");

                    b.Navigation("ProductFiles");

                    b.Navigation("ProductTags");

                    b.Navigation("ProductViews");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("App.Domain.Core.Product.Entities.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
